[robot]
base_link = "base_link"
description = "rrr.urdf.xacro"
disable_collisions = "rrr.srdf.xacro"
mappings = { mobile_base_type = "planar" }

[group.arm]
joints = ["planar_joint", "joint1", "joint2", "joint3"]
tcp_link_name = "end_effector"

named_states = { home = [
  0.0, # x
  0.0, # y
  0.0, # theta
  0.0, # joint1
  0.0, # joint2
  0.0, # joint3
] }

[motion_model]
# Maybe create differential_drive as well?
planar_joint = "reeds_shepp"
# planar_joint = "dubins"

[acceleration_limits]
joint1 = 1.0
joint2 = 1.0
joint3 = 1.0
planar_joint = 1.0
