[robot]
base_link = "base_link"
description = "rrr.urdf.xacro"
disable_collisions = "rrr.srdf.xacro"
mappings = { mobile_base_type = "floating" }

[group.arm]
joints = ["floating_joint", "joint1", "joint2", "joint3"]
tcp_link_name = "end_effector"
named_states = { home = [
  0.0, # x
  0.0, # y
  0.0, # z
  0.0, # rx
  0.0, # ry
  0.0, # rz
  1.0, # rw
  0.0, # joint1
  0.0, # joint2
  0.0, # joint3
] }

[motion_model]
floating_joint = "vana_owen"

[acceleration_limits]
joint1 = 1.0
joint2 = 1.0
joint3 = 1.0
floating_joint = 1.0
