[robot]
base_link = "world"
description = "kinova.urdf.xacro"
disable_collisions = "kinova.srdf.xacro"

[group.arm]
joints = [
  "joint_1",
  "joint_2",
  "joint_3",
  "joint_4",
  "joint_5",
  "joint_6",
  "joint_7",
]
tcp_link_name = "tcp_link"
named_states = { home = [0.0, 0.0, -3.14, -1.57, 0.0, 0.0, 1.57] }

[group.gripper]
joints = ["finger_joint"]


# URDF doesn't provide acceleration limits
[acceleration_limits]
joint_1 = 1.0
joint_2 = 1.0
joint_3 = 1.0
joint_4 = 1.0
joint_5 = 1.0
joint_6 = 1.0
joint_7 = 1.0
# I couldn't find the value for finger_joint in the official specifications
finger_joint = 1.0
