[robot]
base_link = "universe"
description = "acrobot.xml"
disable_collisions = "acrobot.srdf.xacro"

[group.arm]
joints = ["elbow"]
named_states = { home = [0.0] }

[acceleration_limits]
elbow = 1.0
