[robot]
base_link = "panda_link0"
description = "robot-descriptions::panda_description"
disable_collisions = "panda.srdf.xacro"
mappings = { prefix = "panda_" }

[group.arm]
joints = [
  "panda_joint1",
  "panda_joint2",
  "panda_joint3",
  "panda_joint4",
  "panda_joint5",
  "panda_joint6",
  "panda_joint7",
]
tcp_link_name = "panda_hand_tcp"

named_states = { home = [0.0, -0.785, 0.0, -2.356, 0.0, 1.571, 0.785] }

# URDF doesn't provide acceleration limits
# https://frankaemika.github.io/docs/control_parameters.html#limits-for-panda
# We are using the values from MoveIt configs for now
[acceleration_limits]
panda_joint1 = 3.75
panda_joint2 = 1.875
panda_joint3 = 2.5
panda_joint4 = 3.125
panda_joint5 = 3.75
panda_joint6 = 5.0
panda_joint7 = 5.0
panda_finger_joint1 = 1.0
