[robot]
base_link = "base"
description = "robot-descriptions::fr3_mj_description"
disable_collisions = "fr3.srdf.xacro"

[group.arm]
joints = [
  "fr3_joint1",
  "fr3_joint2",
  "fr3_joint3",
  "fr3_joint4",
  "fr3_joint5",
  "fr3_joint6",
  "fr3_joint7",
]
tcp_link_name = "attachment_site"

named_states = { home = [0.0, -0.785, 0.0, -2.356, 0.0, 1.571, 0.785] }

# URDF doesn't provide acceleration limits
# https://frankaemika.github.io/docs/control_parameters.html#limits-for-panda
# We are using the values from MoveIt configs for now
[acceleration_limits]
fr3_joint1 = 3.75
fr3_joint2 = 1.875
fr3_joint3 = 2.5
fr3_joint4 = 3.125
fr3_joint5 = 3.75
fr3_joint6 = 5.0
fr3_joint7 = 5.0
